Trees/C++/1_Symmetric_Tree.cpp

Fixes #47 
@SnehaAgarwal361 @ujju20 Kindly check

Create 1_Symmetric_Tree.cpp under LGMSOC21

---

Linked List/C++/3. Reverse a Linked List.cpp

Fixes issue #67 
Added code for 3. Reverse Linked List following all the mentioned guidelines
Type of change
New feature

Reverse Linked List

---

Linked List/C++/4_Palindrome_Linked_List.cpp

Fixes #68 
@ujju20 Kindly Check

Create 4_Palindrome_Linked_List.cpp under LGMSOC21

---

Trees/C++/Lowest Common Ancestor.cpp

Fixes #95 
Code added for  Lowest Common Ancestor in C++.

Lowest Common Ancestor

---

Math/C++/4_Excel_Sheet_Column_Title.cpp

Fixes #90 and #115 
@YashThakare Kindly check again. Sorry for the issue last time.

Create 4_Excel_Sheet_Column_Title.cpp under LGMSOC21

---

Bit-Manipulation/Java/Power Of Two.java

Fixes #56 
@ujju20  please review it.

Power_of_Two.java

---

Queue/C++/4_Number_Of_Students_Unable_To_Eat_Lunch(QUEUE).cpp

Fixes #52 
@Sargam-Agarwal Kindly Check.
Please focus on the Time complexity part at the end of the document... I think it may require some more thought.

Create 4_Number_Of_Students_Unable_To_Eat_Lunch(QUEUE).cpp under LGMSOC21

---

Bit-Manipulation/Java/Number_Complement.java

Fixes #58 
Java solution for "Number Complement".

Number_Complement.java

---

Math/C++/2_Count_Prime.cpp
Math/C++/count_prime.cpp

Fixes #88 
**Type of change**
New feature 
**Checklist:**

Count_Prime_Number_C++ #88

---

Dynamic Programming/C++/7_Climbing_Stairs.cpp

Fixes #86 
@YashThakare Kindly check.

Create 7_Climbing_Stairs.cpp under LGMSOC21

---

Linked List/Java/5. Delete a Node in a Linked List.java

My code for deleting a node in a linked list in Java

Create 5. Delete a Node in a Linked List.java

---

Math/C++/2_Count_Prime.cpp

@YashThakare ,pls check this one ,I have made the changes.

Prime Numbers C++ #88

---

Math/Java/2_Count_Primes.java

Fixes #88 
New Program as Feature
Follows all the rules.

Count Primes using Java

---

Stack/C++/2_Reorder_List.cpp

Fixes #99 
@SnehaAgarwal361  
Kindly check, focusing on the complexity analysis part... I feel it might need some more thoughts.

Create 2_Reorder_List.cpp under LGMSOC21

---

Bit-Manipulation/Java/6. Check whether a number is power of four.java

My code for this problem in Java

Create 4. Check whether a number is a power of four

---

Bit-Manipulation/C++/numbers_complement.cpp

number  complement

---

Math/C++/5_Factorial_Trailing_Zeroes.cpp

Factorial Trailing Zeroes

---

Dynamic Programming/C++/4_Trapping_Rain_Water.cpp

Trapping Rain Water 

---

Array/C++/1_Valid_Sudoku.cpp

Fixes #131 
@sameeksharl Kindly check.

Create 1_Valid_Sudoku.cpp under LGMSOC21

---

Linked List/C++/5_Delete_a_Node_in_a_Linked_List.cpp

@ujju20 ,I am not able to make changes in the old PR ,so created a new PR ,sorry for the inconvenience.

Delete a Node in a Linked List (LINKED LIST) #69

---

Dynamic Programming/Java/1. Coin Change (DP)

My code for the problem, coin change

Create 1. Coin Change (DP)

---

Math/Java/3_Permutation Sequence

This pull request is generated for the issue Fixes #89 
I have added the solution in Java and tried to add comments wherever necessary.
Kindly review this pr.
THANK YOU!

Code written for 3_Permutation Sequence

---

Trees/Java/4_Validate Binary Search Tree (TREES)

This pull request is generated for the issue Fixes #94  
I have added the solution in Java and tried to add comments wherever necessary.
Kindly review this pr.
THANK YOU!

4.Validate Binary Search Tree

---

Stack/C++/4_Basic Calculator II.cpp

Fixes #97
Code added  for Basic Calculator II in C++.

Basic Calculator II

---

Array/C++/2_Unique_Paths.cpp
Dynamic Programming/C++/2_Unique_Paths.cpp

Fixes #81 
@YashThakare Kindly check

Create 2_Unique_Paths.cpp under LGMSOC21

---

Bit-Manipulation/C++/2_Add Binary.cpp

 Add Binary Numbers(BIT-MANIPULATION)

---

Bit-Manipulation/C++/Problem 5 (Power Of Four).cpp

This pull request is generated for the issue fixed #59  
I have added the problem in C++, and tried to add comments where necessary. 
Kindly review this pr.
THANK YOU!

Added Problem Power of Four

---

Dynamic Programming/Java/Trapping Rain Water.java

Java-Solution "Trapping Rain Water"

---

Dynamic Programming/Python/Trapping_rainwater.py

Added trapping rainwater in python.

---

Bit-Manipulation/Java/4_Counting_Bits.java

Fixes #57 
Add Program as Feature
Made Required Changes @ujju20 
Followed guidelines of readme file

Counting bits of a number using java

---

Stack/C++/5_Remove All Adjacent Duplicates In String.cpp

. Remove-all-adjacent-duplicates-in-string(STACK)

---

Heap/C++/4_Relative Ranks.cpp

4_Relative Ranks

---

Array/C++/3_Merge_Sorted_Array.cpp

Fixes #129 
@sameeksharl Kindly check

Create 3_Merge_Sorted_Array.cpp under LGMSOC21

---

Math/Java/5_Factorial_Trailing_Zeroes.java

Java-Solution "Factorial Trailing Zeroes"

---

Math/Python/5_Factorial_Trailing_Zeroes.py

Fixes #91
Added Factorial Trailing Zeroes Program in Python Language.
please review it.

Added Factorial Trailing Zeroes in python

---

Math/Java/4_Excel_Sheet_Column_Title.java

Fixes #90.
Added Excel Sheet Column Title Program in JAVA.
Please review it.

Added Excel Sheet Column Title in Java

---

Stack/C++/9_Design_a_stack_with_increment_operation.cpp

Design a stack with increment operation

---

Math/Python/4_Excel_Sheet_Column_Title.py

Fixes #90
Added Excel Sheet Column Title program in Python.
please review it.

Added Excel Sheet Column Title in Python

---

Math/C++/1_Rectangle_area.cpp

Rectangle Area

---

Math/Java/8_ Prime_Palindrome

Java Solution " Prime Palindrome'

---

Bit-Manipulation/Java/4 _Counting_Bits_of_Number.java

Fixes #57 
Add Program as Feature
Follows all guidelines
Used Bit Manipulation Method like using bitwise& operator , I solved the program

Counting Bits of Number using Java

---

Hashing/C++/6. Maximum Length of Repeated Subarray (HASHING).cpp

Added solution for "Maximum Length of Repeated Subarray" in c++.
fixes #219

6. Maximum Length of Repeated Subarray (HASHING)

---

Hashing/C++/3_Subtree of Another Tree.cpp

3_Subtree Of Another tree

---

Array/Python/Sort-an-array(Heap).py

Python File Added

---

Hashing/C++/7.Repeated DNA Sequences.cpp

Repeated DNA Sequences

---

Linked List/C++/9_Split_Linked List in Parts.cpp

9.Split linked lists in parts

---

Stack/Java/2_Reorder_List.java

java-Solution "Reorder List"

---

Bit-Manipulation/C++/8_Binary_Gap.cpp

8.Binary Gap

---

Heap/C++/6.Reduse_Array_Size_To_Half.cpp
Heap/C++/7.Sort_Characters_By_Frequency.cpp

- added c++ solution for 7th question in heap
- @Debashish-hub Review It

7. Sort Characters By Frequency (HEAP) C++ Solution

---

Heap/C++/3.Last Stone Weight.cpp

Last Stone Weight

---

Math/Java/10_Greatest Common Divisor of Strings (MATH)

This pull request is generated for the issue Fixes #203 
I have added the solution in Java and tried to add comments wherever necessary.
Kindly review this pr.
THANK YOU!

10_Greatest Common Divisor of Strings (MATH)

---

Hash Table/C++/2. Intersection of two linked lists (HASHTABLE).cpp

Added solution to problem "2. Intersection of two linked lists (HASHTABLE)"
fixes #249

2. Intersection of two linked lists (HASHTABLE)

---

Queue/C++/5. Reveal_Cards _In_Increasing_Order.cpp

Added C++ solution for 5. Reveal Cards In Increasing Order in Queue , Review it.

5. Reveal Cards In Increasing Order (Queue) C++ solution added

---

Hash Table/C++/Count the Number of Consistent Strings.cpp

5. Count the number of consistent strings (HASHTABLE)

---

Hash Table/C++/10.Majority_Element.cpp

- added c++ solution for 10. Majority element in Hashtable
- @Sargam-Agarwal Review It

10. Majority element (HASHTABLE) C++ solution 

---

Hashing/C++/5. Check If a String Contains All Binary Codes of Size K.cpp

- added c++ solution for 5th question in hashing
- @Debashish-hub Review It .

5.Check If a String Contains All Binary Codes of Size K (HASHING)  C++ solution added

---

Array/Java/1_Valid_Sudoku.java

Java-solution "valid sudoku"

---

Dynamic Programming/C++/1.Coins Change.cpp

- added c++ solution for first DP problem - Coin Change 
- @YashThakare Review It .

1. Coin Change (Dynamic Programming)  C++ solution

---

Math/Java/9 Valid Square.java

This file was created by Mitadru Datta which includes the entire java
code for solving the problem "Valid Square" hosted on LeetCode.

Valid Square (MATH) Fixes #202

---

Trees/C++/9_ All Possible Full Binary Trees.cpp

9_ All Possible Full Binary Trees.cpp

---

Trees/C++/2_Invert_Binary_Tree.cpp

2_Invert_Binary_Tree.cpp

---

Trees/C++/4_Validate_Binary_Search_Tree.cpp

4_Validate_Binary_Search_Tree.cpp

---

Trees/C++/10_Binary_Tree_Right_Side_View.cpp

 10_Binary_Tree_Right_Side_View.cpp

---

Trees/C++/8_Deepest_Leaves_ Sumcpp.cpp

8.Deepest Leaves Sum

---

Hash Table/C++/4. Find all numbers disappeared in an array (HASHTABLE).cpp

Added solution for "4. Find all numbers disappeared in an array (HASHTABLE)" in C++
fixes #251

4. Find all numbers disappeared in an array (HASHTABLE)

---

Math/C++/3_Permutation_Sequence.cpp

- added c++ solution for 3. permutation sequence in math
- @YashThakare Review It.

3. Permutation Sequence (MATH ) C++ solution 

---

Bit-Manipulation/C++/10.Find the Duplicate Number.cpp

- added c++ solution for 10th question in bit-manipulation
- @vilsi12 @ujju20 Review It .

10. Find The Duplicate Number (BIT-MANIPULATION) C++ Solution

---

Stack/10_Backspace String Compare.cpp

10_Backspace String Compare

---

Hash Table/Python/Majority Element.py

5. Majority Element (HASHTABLE)

---

Linked List/Java/9_Split_Linked_List_in_Parts.java

Java solution "Split Linked List in Parts"

---

Dynamic Programming/C++/8_Longest_Increasing_Subsequence.cpp

Added code for Longest Increasing Subsequence to the folder C++/Dynamic Programming.

Added code for Longest Increasing Subsequence.

---

Matrix/01_MatrixAdd.cpp
Matrix/02_MagicSquare.cpp
Matrix/03_MaxColEle.cpp
Matrix/04_MaxElement.cpp
Matrix/05_GreatestSum.cpp
Matrix/06_MaxRowEle.cpp
Matrix/07_SumRows.cpp
Matrix/08_SumZigZag.cpp
Matrix/C++/01_MatrixAdd.cpp
Matrix/C++/02_MagicSquare.cpp
Matrix/C++/03_MaxColEle.cpp
Matrix/C++/04_MaxElement.cpp
Matrix/C++/05_GreatestSum.cpp
Matrix/C++/06_MaxRowEle.cpp
Matrix/C++/07_SumRows.cpp
Matrix/C++/08_SumZigZag.cpp

Please add all labels related to Hacktoberfest2022 labels too

Added basic to intermediate matrix problems in c++
